export const SPELLS = {
  autoAttack: {
    id: 'autoAttack',
    name: 'Auto Attack',
    school: 'physical',
    description: 'Turn automatic melee swings at your target on or off.',
    effect: 'damage',
    amount: 8,
    castTimeMs: 0,
    cooldownMs: 0,
    manaCost: 0,
    maxRange: 5,
    validTargets: ['hostile'],
    requiresFacing: true,
    isAutoAttack: true,
    swingIntervalMs: 2000,
  },
  strike: {
    id: 'strike',
    name: 'Strike',
    school: 'physical',
    description: 'Hit your target with your weapon. Also starts Auto Attack.',
    effect: 'damage',
    amount: 15,
    castTimeMs: 0,
    cooldownMs: 4000,
    manaCost: 5,
    maxRange: 5,
    validTargets: ['hostile'],
    requiresFacing: true,
    startsAutoAttack: true,
  },
  firebolt: {
    id: 'firebolt',
    name: 'Firebolt',
    school: 'fire',
    description: 'Hurl a bolt of fire at your target.',
    effect: 'damage',
    amount: 25,
    castTimeMs: 1500,
    cooldownMs: 0,
    manaCost: 10,
    maxRange: 30,
    validTargets: ['hostile'],
    requiresFacing: true,
  },
  iceLance: {
    id: 'iceLance',
    name: 'Ice Lance',
    school: 'frost',
    description: 'Throw a shard of ice at your target at once.',
    effect: 'damage',
    amount: 12,
    castTimeMs: 0,
    cooldownMs: 6000,
    manaCost: 8,
    maxRange: 30,
    validTargets: ['hostile'],
    requiresFacing: true,
  },
  mend: {
    id: 'mend',
    name: 'Mend',
    school: 'nature',
    description: 'Heal a friendly target. Heals you if you have no friendly target.',
    effect: 'heal',
    amount: 30,
    castTimeMs: 2000,
    cooldownMs: 0,
    manaCost: 15,
    maxRange: 30,
    validTargets: ['self', 'friendly'],
    requiresFacing: false,
  },
};
