export const SPELLS = {
  autoAttack: {
    id: 'autoAttack',
    name: 'Auto Attack',
    school: 'physical',
    description: 'Turn automatic melee swings at your target on or off.',
    effect: 'damage',
    amount: 8,
    castTimeMs: 0,
    cooldownMs: 0,
    manaCost: 0,
    maxRange: 5,
    validTargets: ['hostile'],
    requiresFacing: true,
    isAutoAttack: true,
    swingIntervalMs: 2000,
  },
  strike: {
    id: 'strike',
    name: 'Strike',
    school: 'physical',
    description: 'Hit your target with your weapon. Also starts Auto Attack.',
    effect: 'damage',
    amount: 15,
    castTimeMs: 0,
    cooldownMs: 4000,
    manaCost: 5,
    maxRange: 5,
    validTargets: ['hostile'],
    requiresFacing: true,
    startsAutoAttack: true,
  },
  firebolt: {
    id: 'firebolt',
    name: 'Firebolt',
    school: 'fire',
    description: 'Hurl a bolt of fire at your target.',
    effect: 'damage',
    amount: 25,
    castTimeMs: 1500,
    cooldownMs: 0,
    manaCost: 10,
    maxRange: 30,
    validTargets: ['hostile'],
    requiresFacing: true,
    projectileSpeed: 30,
  },
  iceLance: {
    id: 'iceLance',
    name: 'Ice Lance',
    school: 'frost',
    description: 'Throw a shard of ice at your target at once.',
    effect: 'damage',
    amount: 12,
    castTimeMs: 0,
    cooldownMs: 6000,
    manaCost: 8,
    maxRange: 30,
    validTargets: ['hostile'],
    requiresFacing: true,
    projectileSpeed: 30,
  },
  mend: {
    id: 'mend',
    name: 'Mend',
    school: 'nature',
    description: 'Heal a friendly target. Heals you if you have no friendly target.',
    effect: 'heal',
    amount: 30,
    castTimeMs: 2000,
    cooldownMs: 0,
    manaCost: 15,
    maxRange: 30,
    validTargets: ['self', 'friendly'],
    requiresFacing: false,
  },
  bite: {
    id: 'bite',
    name: 'Bite',
    school: 'physical',
    description: 'A wolf bites its target over and over.',
    effect: 'damage',
    amount: 5,
    castTimeMs: 0,
    cooldownMs: 0,
    manaCost: 0,
    maxRange: 5,
    validTargets: ['hostile'],
    requiresFacing: true,
    isAutoAttack: true,
    swingIntervalMs: 2000,
    isCreatureOnly: true,
  },
  slash: {
    id: 'slash',
    name: 'Slash',
    school: 'physical',
    description: 'A bandit slashes its target with a sword.',
    effect: 'damage',
    amount: 7,
    castTimeMs: 0,
    cooldownMs: 0,
    manaCost: 0,
    maxRange: 5,
    validTargets: ['hostile'],
    requiresFacing: true,
    isAutoAttack: true,
    swingIntervalMs: 2000,
    isCreatureOnly: true,
  },
  heavySlash: {
    id: 'heavySlash',
    name: 'Heavy Slash',
    school: 'physical',
    description: 'The bandit leader cuts deep with a heavy blade.',
    effect: 'damage',
    amount: 10,
    castTimeMs: 0,
    cooldownMs: 0,
    manaCost: 0,
    maxRange: 5,
    validTargets: ['hostile'],
    requiresFacing: true,
    isAutoAttack: true,
    swingIntervalMs: 2000,
    isCreatureOnly: true,
  },
  alphaBite: {
    id: 'alphaBite',
    name: 'Savage Bite',
    school: 'physical',
    description: 'An alpha wolf bites hard.',
    effect: 'damage',
    amount: 8,
    castTimeMs: 0,
    cooldownMs: 0,
    manaCost: 0,
    maxRange: 5,
    validTargets: ['hostile'],
    requiresFacing: true,
    isAutoAttack: true,
    swingIntervalMs: 2000,
    isCreatureOnly: true,
  },
  venomBite: {
    id: 'venomBite',
    name: 'Venom Bite',
    school: 'physical',
    description: 'A giant cave spider sinks its fangs into its target.',
    effect: 'damage',
    amount: 14,
    castTimeMs: 0,
    cooldownMs: 0,
    manaCost: 0,
    maxRange: 5,
    validTargets: ['hostile'],
    requiresFacing: true,
    isAutoAttack: true,
    swingIntervalMs: 2000,
    isCreatureOnly: true,
  },
  spiderlingBite: {
    id: 'spiderlingBite',
    name: 'Spiderling Bite',
    school: 'physical',
    description: 'A spiderling nips at its target.',
    effect: 'damage',
    amount: 5,
    castTimeMs: 0,
    cooldownMs: 0,
    manaCost: 0,
    maxRange: 5,
    validTargets: ['hostile'],
    requiresFacing: true,
    isAutoAttack: true,
    swingIntervalMs: 2000,
    isCreatureOnly: true,
  },
  crushingBite: {
    id: 'crushingBite',
    name: 'Crushing Bite',
    school: 'physical',
    description: 'The Broodmother crushes her target in her jaws.',
    effect: 'damage',
    amount: 12,
    castTimeMs: 0,
    cooldownMs: 0,
    manaCost: 0,
    maxRange: 5,
    validTargets: ['hostile'],
    requiresFacing: true,
    isAutoAttack: true,
    swingIntervalMs: 2000,
    isCreatureOnly: true,
  },
  poisonBite: {
    id: 'poisonBite',
    name: 'Poison Bite',
    school: 'nature',
    description: 'The Broodmother poisons her target, which then takes damage over time.',
    effect: 'damage',
    amount: 6,
    castTimeMs: 0,
    cooldownMs: 8000,
    manaCost: 0,
    maxRange: 5,
    validTargets: ['hostile'],
    requiresFacing: true,
    isCreatureOnly: true,
    // After the hit, the poison deals this damage each interval, this many times.
    damageOverTime: { amount: 3, intervalMs: 2000, ticks: 5 },
  },
};
